ajax/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^get$', get, name='get'),
    url(r'^config$', config, name='config')
]

base/urls.py
"""from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.Home, name="home")
]"""

dashboard/urls.py
from django.conf.urls import url
import views
from rest_framework.routers import DefaultRouter

dashboard_router = DefaultRouter()
dashboard_router.register(r'^dashboard-details', views.DashboardAPIView, base_name="dashboard-details")

urlpatterns = [
    url(r'^designer/?$', views.DashboardDesigner.as_view(), name='designer'),
    url(r'^list/?$', views.DashboardList.as_view(), name='list'),
    url(r'^create/?$', views.get_dashboard_data, name='create'),
    url(r'^delete/(?P<pk>[\w]+)/?$', views.delete_dashboard_data, name='delete'),
    url(r'^dashboard/(?P<pk>[\w]+)/?$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^load/(?P<pk>[\w]+)/?$', views.load_dashboard_data, name='load'),
] + dashboard_router.urls

graphs/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url('^$', Home.as_view(), name="home"),
    url(r'^scatter/?$', Scatter.as_view(), name='scatter'),
    url(r'^line/?$', Line.as_view(), name="line"),
    url(r'^bar/?$', Bar.as_view(), name='bar'),
    url(r'^compound/?$', Compound.as_view(), name='compound'),
    url(r'^animated/?$', AnimatedLine.as_view(), name="animated"),
]

plantlink_scada/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^graphs/', include("graphs.urls", namespace="graphs")),
    url(r'^ajax/', include("ajax.urls", namespace="ajax")),
    url(r'^widgets/', include('svg_widgets.urls', namespace='widgets')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^scada/', include('scada.urls', namespace='scada')),
] + static.static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

scada/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^creator/?$', views.ScadaCreator.as_view(), name="creator")
]

svg_widgets/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', Home.as_view(), name="home"),
    url(r'^dial$', Dial.as_view(), name="dial"),
    url(r'^slider$', Slider.as_view(), name="slider"),
    url(r'^graphs$', Graphs.as_view(), name="graphs"),
    url(r'^misc$', Misc.as_view(), name="misc"),
    url(r'^get-data$', get_val, name="get-data"),
    url(r'^make-conn$', make_conn, name="make-conn")

]

ajax/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

base/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import datetime
import django.utils.timezone
from  django.conf import settings

# Create your models here.
class Dashboard(models.Model):
    created = models.DateField(auto_now=True)
    config_file = models.FilePathField(path=settings.BASE_DIR)
    name = models.CharField(max_length=64)

graphs/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

react_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

scada/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

svg_widgets/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

ajax/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
import serial

conn = serial.Serial()

def get(request):
    global conn
    if not conn.is_open:
        return HttpResponse(-1)
    
    val = ""
    count = 0
    while not val.startswith("H"):
        conn.write("s")
        val = conn.read(3)
        count += 1
        if count > 10:
            return HttpResponse(-2)
    toInt= ord(val[1]) * 256 + ord(val[2])
    resp = (toInt / 1024.0) * 10
    return HttpResponse(resp)

def config(request):
    global conn
    port = request.POST.get("port-no")
    conn.port = "COM" + port
    conn.baudrate = 9600
    conn.open()
    return HttpResponseRedirect(reverse("widgets:home"))

base/views.py
from django.shortcuts import render

# Create your views here.

dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, JsonResponse
import os
from django.views.generic import TemplateView, ListView, DetailView
from rest_framework import viewsets
from models import Dashboard
from serializers import DashboardSerializer
import json
from django.shortcuts import get_object_or_404

class DashboardDesigner(TemplateView):
    template_name = os.path.join("dashboard", "designer.html")


class DashboardList(ListView):
    template_name = os.path.join("dashboard", "list.html")
    model = Dashboard
    paginate_by=5

class DashboardAPIView(viewsets.ModelViewSet):
    serializer_class = DashboardSerializer
    queryset = Dashboard.objects.all()

class DashboardView(DetailView):
    template_name = os.path.join("dashboard", "dashboard.html")
    model = Dashboard

def load_dashboard_data(request, pk):
    dash = Dashboard.objects.get(pk=pk)
    fp = open("media/" + dash.config_file,'r')
    resp = json.load(fp)
    return JsonResponse(resp)

def delete_dashboard_data(request, pk):
    dash = Dashboard.objects.get(pk=pk)
    os.remove(os.path.join("media", dash.config_file))
    dash.delete()
    return HttpResponseRedirect(reverse("dashboard:list"))
    
def get_dashboard_data(request):
    dash_data = json.loads(request.POST["data"])
    print dash_data
    filename =  dash_data["name"] + "_config.json"
    with open("media/" + filename, 'w') as conf:
        json.dump(dash_data, conf)

    Dashboard(name=dash_data["name"],
                config_file=filename).save()

    return HttpResponseRedirect(reverse("dashboard:list"))

graphs/views.py
import os 

from django.shortcuts import render
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = os.path.join("graphs", "home.html")

class Bar(TemplateView):
    template_name = os.path.join("graphs", "bar.html")

class Line(TemplateView):
    template_name = os.path.join("graphs", "line.html")

class Scatter(TemplateView):
    template_name = os.path.join("graphs", "scatter.html")

class Compound(TemplateView):
    template_name = os.path.join("graphs", "compound.html")

class AnimatedLine(TemplateView):
    template_name = os.path.join("graphs", "animated.html")

scada/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import TemplateView
import os

class ScadaCreator(TemplateView):
    template_name = os.path.join("scada", 'creator.html')

    

svg_widgets/views.py
import os

from django.shortcuts import render, reverse
from django.views.generic import TemplateView
from django.http import HttpResponse, HttpResponseRedirect
import json 
import serial
config = {
    "conn": None,
    "port": "COM1"
}


class Home(TemplateView):
    template_name = os.path.join("svg_widgets", "home.html")
    

class Dial(TemplateView):
    template_name = os.path.join("svg_widgets", "dial.html")

class Slider(TemplateView):
    template_name = os.path.join("svg_widgets", "slider.html")

class Graphs(TemplateView):
    template_name = os.path.join("svg_widgets", "graphs.html")

class Misc(TemplateView):
    template_name = os.path.join("svg_widgets", "misc.html")

def get_val(request):
    global config

    if not config["conn"]:
        return HttpResponse(json.dumps({"reading": -1}), content_type="application/json")
    
    data = {}
    reading = ""
    count = 0
    while count < 10:
       reading =  config["conn"].read(6)
       count += 1
    

    data["reading"] = 10 * (reading[reading.find("h"):reading.find("f")] / 1024)
    
    return HttpResponse(json.dumps(data), content_type="application/json")

def make_conn(request, port=1):
    global config
    config["conn"] = serial.Serial()
    config["port"] = "COM" + str(port)

    config["conn"].port = config["port"]
    config["conn"].baudrate = 9600
    try:
        config["conn"].open()
    except:
        config["conn"] = None

    return HttpResponseRedirect(reverse("widgets:dial"))

base/templates/base.html
{% load static %}
<Doctype html>
<html>
    <head>
            <link rel="stylesheet" href="{% static 'base/bootstrap/css/bootstrap.min.css' %}" >
            <script src="{% static 'base/jquery-2.2.2.js' %}" ></script>
            <script src="{% static 'base/bootstrap/js/bootstrap.min.js' %}" ></script>
            <script src="{% static 'base/d3.min.js' %}"></script>
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

dashboard/templates/dashboard/dashboard.html
{% extends "base.html" %}
{% block content %}
{% load render_bundle from webpack_loader %}
{% csrf_token %}

<div class="jumbotron">
    <div class="container">
        <h1>Dashboard</h1>
        <h4>Name: {{object.name}}</h4>
        <h4>Date Created: {{object.created}}</h4>        
    </div>
</div>

<div id="root"></div>

{% render_bundle 'running_dash' %}
{% endblock %}

dashboard/templates/dashboard/designer.html
{% extends "base.html" %}
{% block content %}
{% load render_bundle from webpack_loader %}
{% csrf_token %}
<h3>Dashboard Designer</h3>
<div id="root"></div>
{% render_bundle "dashboard" %}
{% endblock %}

dashboard/templates/dashboard/list.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <div class="container">
        <h1>Dashboard List</h1>
        <p>List of created Dashboards</p>
        <p>
            <a href="{% url 'dashboard:designer' %}" class="btn btn-primary btn-lg">Create New</a>
        </p>
    </div>
</div>
<style>
    .head {
        background-color: blue;
        margin: 2px;
        padding: 5px;
        color: white;
        border: 1px solid white;
        text-align: center;

    }
</style>
<div>
    {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="previous"><a href="?page={{page_obj.previous_page_number}}">
                <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                </a></li>
                {% else %}
                <li class="disabled"><span>
                <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                </span></li>
                {% endif %}
    
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                    <li class="active"><span>{{i}}</span></li>
                    {% else %}
                    <li><a href="?page={{i}}">{{i}}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="next"><a href="?page={{page_obj.next_page_number}}">
                <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </a></li>
                {% else %}
                <li class="disabled"><span>
                <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </span></li>
                {% endif %}
                
            </ul>
            {% endif %}
</div>
<div class="well">
        <table class="table">
                <thead>
                    <tr>
                        <td class="head">Date Created</td>
                        <td class="head">Name</td>
                        <td class="head">Actions</td>
                    </tr>
                </thead>
                <tbody>
                    {% for dash in object_list %}
                    <tr>
                        <td>{{dash.created}}</td>
                        <td>{{dash.name}}</td>
                        <td>
                            
                            <a href="{% url 'dashboard:dashboard' dash.pk %}" class="btn btn-primary">
                                <span class="glyphicon glyphicon-th" aria-hidden="true"></span>        
                        </a>
                        <a href="{% url 'dashboard:delete' dash.pk %}" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>        
                    </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
</div>

{% endblock %}

dashboard/templates/dashboard/sample.html
<a class="btn btn-primary" data-toggle="modal" href='#modal-id'>Trigger modal</a>
<div class="modal fade" id="modal-id">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>


/**
         *prototypeRow = {
            id: 0,
            cols: []
        };

        prototypeCol = {
            id: 0,
            hasWidget: false,
            widget: {}
        }; 
         */

         
         <div class="panel panel-default">
             <div class="panel-body">
                Basic panel example
             </div>
         </div>
         
         
         <div class="panel panel-primary">
               <div class="panel-heading">
                     <h3 class="panel-title">Panel title</h3>
               </div>
               <div class="panel-body">
                     Panel content
               </div>
         </div>
         

dashboard_designer/templates/dashboard_designer/home.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load static %}
{% block content %}
<h3>Dashboard Designer</h3>
<div id="root"></div>
{% render_bundle "dashboard" %}
{% endblock %}

graphs/templates/graphs/animated.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h3>Animated Line</h3>
<style>
    .line {
        fill: none;
        stroke: steelblue;
        stroke-width: 5px;
    }
</style>
<script type="text/javascript">
// initializing size params
var margin = {top:20, right:20, bottom:30, left: 50},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

//set the range
var x = d3.scaleLinear()
    .range([0, width])
    .domain([0,10]);

var y = d3.scaleLinear()
    .range([height, 0])
    .domain([0, 1]);//note opposite direction

//data array
var data = new Array();

//line
var valueline = d3.line()
    .x(function(d, i){ return x(i); }) //d.year added to the scale object
    .y(function(d, i){ return y(d); });

//adding the svg region
var svg = d3.select("body").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
    .append("g")
        .attr("transform", "translate(" +margin.left+","+ margin.right+")");
    svg.append("rect")
        .attr("x", 0)
        .attr("y", 0)
        .attr("width", width)
        .attr("height", height)
        .attr("fill", "black");

    svg.append("g")
        .attr("transform", " translate(0,"+ height+")")
        .call(d3.axisBottom().scale(x));

    svg.append("g")
        .call(d3.axisLeft(y));

var path = svg.append("path")
            .data([data])
            .attr("class", "line")
            .attr("d", valueline);
            
var pointer = null;

setInterval(function(){
    var last = Math.random();
    data.push(last);

    //pointer
    if(pointer === null){
        pointer = svg.append("circle")
            .attr("fill", "steelblue")
            .attr("cx", x(data.length -2))
            .attr("cy", y(last))
            .attr("r", 10);

    }else {
            ;
    }

    if(data.length > 10){
        data.shift();
        var fill = null;
        if(data[data.length-1] > 0.7){
            fill="red";
        }else if(data[data.length-1] < 0.3){
            fill="steelblue";
        }else{
            fill="yellow";
        }
        pointer.transition().attr("fill", fill)
            .attr("cx", x(data.length -1))
            .attr("cy", y(last));
        //add circle tracker and vertical line
    }
    
    path.transition().attr("d", valueline);

}, 100);
</script>

{% endblock %}

graphs/templates/graphs/bar.html
{% load static %}
<!doctype html>
<html>
    <head>
        <style>
        </style>
        <script src="{% static 'base/d3.min.js' %}"></script>
        <title> Animated bar chart </title>
    </head>
    <body>
        <h3>Animated bar chart</h3>
        <script>
            var w = 500,
                h = 100,
                barPadding = 2;
            var dataset = [7, 9,10,13,20, 13, 19, 21, 22,
                             15, 13, 11]
            var svg = d3.select("body")
                .append("svg")
                .attr("width", w)
                .attr("height", h);

            svg.selectAll("rect")
                .data(dataset)
                .enter()
                .append("rect")
                .attr("x", function(d, i){
                    //top left corner coordinate x-axis
                    return i * (w/ dataset.length);
                })
                .attr("y", function(d){
                    //top left coordinate y-axis
                    // h-d to make it start from the bottom
                    //*3 to match the bar length scaling
                    return h-(d*3);
                })
                .attr("fill", function(d){
                    return "rgb(0,0, " + (d*10)+")";})
                .attr("width", function(d, i){
                    //width of rectangle
                    return (w/ dataset.length - barPadding);
                })
                .attr("height", function(d){
                    //height of rectangle
                    return d*3;
                });
svg.selectAll("text")
    .data(dataset)
    .enter()
    .append("text")
    .text(function(d){ return d;})
    .attr("x", function(d, i){
        //x position of text in the middle
        return i * (w/dataset.length) + (w/dataset.length -barPadding)/2;
    })
    .attr("y", function(d){
        //y position of the text 
        return h - (d * 3) + 15;
    })
    .attr("fill", "white")
    .attr("font-size", "11px")
    .attr("font-family", "sans-serif")
    .attr("text-anchor", "middle");
    //^ text formatting
        </script>
    </body>
</html>

graphs/templates/graphs/compound.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h3>Line</h3>
<style>
    .line {
        fill: none;
        stroke: green;
        stroke-width: 5px;
    }
</style>
<script type="text/javascript">
// initializing size params
var margin = {top:20, right:20, bottom:30, left: 50},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

//set the range
var x = d3.scaleTime().range([0, width]);
var y = d3.scaleLinear().range([height, 0]);//note opposite direction

//line
var valueline = d3.line()
    .x(function(d){ return x(d.year); }) //d.year added to the scale object
    .y(function(d){ return y(d.population); });

//adding the svg region
var svg = d3.select("body").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
    .append("g")
        .attr("transform", "translate(" +margin.left+","+ margin.right+")");
    
// ensures that the dat from the csv is formatted correctly
d3.csv("{% static 'data.csv' %}", function(error, data){
data.forEach(function(d){
            d.year = d.year;
            d.population = d.population;
        });
        
x.domain(d3.extent(data, function(d){ return d.year; }));
y.domain([0, d3.max(data, function(d){ return d.population; })]);

svg.selectAll("rect")
.data(data)
.enter()
.append("rect")
.attr("width", function(d, i){
    return (width / data.length );
})
.attr("height", function(d){
    return height - y(d.population);
})
.attr("x", function(d, i){
    return x(d.year) - ((width / data.length) / 2);
})
.attr("y", function(d){
    return y(d.population);
})
.attr("fill", "blue");

        svg.append("path")
            .data([data])
            .attr("class", "line")
            .attr("d", valueline);

        svg.selectAll("circle")
            .data(data)
            .enter()
            .append("circle")
            .attr("cx", function(d){
                (d.year);
                return x(d.year);
            })
            .attr("cy", function(d){
                return y(d.population);
            })
            .attr("r", 8)
            .attr("fill", "green");

        


        svg.append("g")
            .attr("transform", " translate(0,"+ height+")")
            .call(d3.axisBottom().scale(x));

        svg.append("g")
            .call(d3.axisLeft(y));
    });
</script>

{% endblock %}

graphs/templates/graphs/home.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load static %}
{% block content %}
<h3>Graph</h3>
<p>Graphing showcase</p>
<div id="react-root"></div>
{% render_bundle 'main' %}
<ul>
    <li><a href="{% url 'graphs:bar' %}">Bar</a></li>
    <li><a href="/graphs/line" >Line</a></li>
    <li><a href="/graphs/scatter">Scatter</a></li>
    <li><a href="/graphs/compound">Compound</a></li>
    <li><a href="/graphs/animated">Animated</a></li>
</ul>


{% endblock %}

graphs/templates/graphs/line.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h3>Line</h3>
<style>
    .line {
        fill: none;
        stroke: green;
        stroke-width: 5px;
    }
</style>
<script type="text/javascript">
// initializing size params
var margin = {top:20, right:20, bottom:30, left: 50},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

//set the range
var x = d3.scaleTime().range([0, width]);
var y = d3.scaleLinear().range([height, 0]);//note opposite direction

//line
var valueline = d3.line()
    .x(function(d){ return x(d.year); }) //d.year added to the scale object
    .y(function(d){ return y(d.population); });

//adding the svg region
var svg = d3.select("body").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
    .append("g")
        .attr("transform", "translate(" +margin.left+","+ margin.right+")");
    
// ensures that the dat from the csv is formatted correctly
d3.csv("{% static 'data.csv' %}", function(error, data){
data.forEach(function(d){
            d.year = d.year;
            d.population = +d.population;
        });
        
x.domain(d3.extent(data, function(d){ return d.year; }));
y.domain([0, d3.max(data, function(d){ return d.population; })]);

        svg.append("path")
            .data([data])
            .attr("class", "line")
            .attr("d", valueline);

        svg.append("g")
            .attr("transform", " translate(0,"+ height+")")
            .call(d3.axisBottom().scale(x));

        svg.append("g")
            .call(d3.axisLeft(y));
    });
</script>

{% endblock %}

graphs/templates/graphs/scatter.html
{% extends "base.html" %}
{% block content %}
<script type="text/javascript">
var dataset = [
    [5, 20], [480, 90], [250, 50], [100, 33], [330, 95],
    [410, 12], [475, 44], [25, 67], [85, 21], [220, 88]
  ];
var w =500,
    h=100,
    margin=25;// used to adjust the scales

var svg = d3.select("body")
    .append("svg")
    .attr("width", w + 2* margin)
    .attr("height", h+ margin);

var xScale = d3.scaleLinear()
    .domain([0, d3.max(dataset, function(d){
        return d[0];
    })])
    .range([0,w]);

var yScale = d3.scaleLinear()
    .domain([0, d3.max(dataset, function(d){ 
        return d[1];
    })])
    .range([h, 0]);

svg.selectAll("circle")
    .data(dataset)
    .enter()
    .append("circle")
    .attr("cx", function(d){ 
        return margin + d[0]; 
    })
    .attr("cy", function(d){
        return d[1];
    })
    .attr("r", function(d){
        //dynamic size
        return Math.sqrt(h - d[1]);
    });

svg.selectAll("text")
    .data(dataset)
    .enter()
    .append("text")
    .text(function(d){
        return d[0] + ", " + d[1];
    })
    .attr("x", function(d){
        
        return margin + d[0];
    })
    .attr("y", function(d){
        return d[1];
    })
    .attr("font-family", "sans-serif")
    .attr("font-size", "11px")
    .attr("fill", "red");

var xAxis = d3.axisBottom(xScale);
var yAxis = d3.axisLeft(yScale);
svg.append("g")
    .attr("transform", "translate("+ 20 +", "+ h +")")
    .call(xAxis);

svg.append("g")
    .attr("transform","translate("+20+", 0)")
    .call(yAxis);

</script>
{% endblock %}

scada/templates/scada/creator.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% block content %}
<div id="root" ></div>
{% render_bundle "scada" %}
{% endblock %}

svg_widgets/templates/svg_widgets/dial.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load static %}
{% block content %}

<h3>SVG Dial</h3>
<div id="react-dial"></div>
<div id="dial-arc"></div>

{% render_bundle "main" %}
{% endblock %}

svg_widgets/templates/svg_widgets/graphs.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load static %}
{% block content %}


<h3>Animated graphs</h3>

<div class="row">
    
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <div id="reactive"></div>        
    </div>
    
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <div id="unshaded"></div>
    </div>
    
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <div id="bar-animated"></div>        
    </div>
    
    
</div>

<h4>Single bar</h4>
<div id="react-root"></div>

{% render_bundle "main" %}
{% endblock %}

svg_widgets/templates/svg_widgets/home.html
{% extends "base.html" %}
{% block content %}
<h3>Widget showcase</h3>
<ul>
    <li><a href="{% url 'widgets:dial' %}" >Radial Dial</a></li>
    <li><a href="{% url 'widgets:slider' %}" >Sliders</a></li>
    <li><a href="{% url 'widgets:graphs' %}" >Graphs</a></li>
    <li><a href="{% url 'widgets:misc' %}">Misc. widgets</a></li>
</ul>
{% endblock %}

svg_widgets/templates/svg_widgets/misc.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load static %}
{% block content %}

<h3 >Active valve with toggle</h3>
<div id="react-valve"></div>

<h3>Value Indicator</h3>
<div id="react-indicator"></div>

<h3>Knob Widget</h3>
<div id="knob"></div>

{% render_bundle "main" %}
{% endblock %}

svg_widgets/templates/svg_widgets/slider.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load static %}
{% block content %}


<h3>Sliders</h3>
<div id="react-slider2"></div>
<div id="react-slider"></div>

{% render_bundle "main" %}
{% endblock %}